describe("Checker game code", () => {
  it("Checkers game play", () => {
    cy.visit("https://www.gamesforthebrain.com/game/checkers/");
    cy.url().should("contain", "gamesforthebrain");
    cy.get('[name="space62"]').should("be.visible").click().and("have.attr", "src", "you2.gif");
    cy.get('[name="space73"]').click();
    cy.wait(2000);
    cy.get('[name="space71"]').should("be.visible").click().and("have.attr", "src", "you2.gif");
    cy.get('[name="space62"]').click();
    cy.wait(2000);
    cy.get('[name="space42"]').should("be.visible").click();
    cy.get('[name="space53"]').click();
    cy.wait(2000);
    cy.get('[name="space31"]').should("be.visible").click();
    cy.get('[name="space42"]').click();
    cy.wait(2000);
    cy.get('[name="space02"]').should("be.visible").click();
    cy.get('[name="space13"]').click();
    cy.wait(2000);
    cy.get('[name="space13"]').should("be.visible").click();
    cy.get('[name="space04"]').click();
    cy.wait(2000);
    cy.get('[name="space40"]').should("be.visible").click();
    cy.get('[name="space31"]').click();
    cy.wait(2000);
    cy.get('[name="space60"]').should("be.visible").click();
    cy.get('[name="space71"]').click();
    cy.wait(2000);
    cy.get('[name="space53"]').should("be.visible").click();
    cy.get('[name="space35"]').click();
    cy.wait(2000);
    cy.get('[name="space04"]').should("be.visible").click();
    cy.get('[name="space15"]').click();
    cy.wait(2000);
    cy.get('[name="space42"]').should("be.visible").click();
    cy.get('[name="space53"]').click();
    cy.wait(2000);
    cy.get('[name="space22"]').should("be.visible").click();
    cy.get('[name="space13"]').click();
    cy.wait(2000);
    cy.get('[name="space15"]').should("be.visible").click();
    cy.get('[name="space26"]').click();
    cy.wait(2000);
    cy.get('[name="space26"]').should("be.visible").click();
    cy.get('[name="space37"]').click().should("have.attr", "src", 'you1k.gif"');
    cy.scrollTo("top");
  });
});
