export const Flightlocators = {
  toclickonBokings: '[data-testid="myBookings-button-large"]',
  toacceptc: "#onetrust-accept-btn-handler",
  toSigninGoogle: '[class="LgbsSe-Bz112c"]',
  toclickonFlight: '[data-testid="menu-link-Flights"]',
  toclickonway: '[class="_15h2k5o0 ioeri02 _15h2k5o1"]',
  toclickmulticity: '[class="_15h2k5o0 ioeri02 _15h2k5o1"]',
  toclickonfrom: '[data-testid="searchForm-singleBound-origin-input"] > .e9xops0 > .css-dyr6gj-container > .css-1ojcpw1 > .css-1hwfws3',
  toclickto: '[class=" css-1hwfws3"]',
  toclicklahore: '[class="css-13877z6"]',
  toclickKarachi: '[class="css-1dq0nfs"]',
  toclickDeprt: '[class="cm3pbi4 _1c374az1 cm3pbi3 _1c374az2"]',
  toclickreturn: '[class="cm3pbi4 _1c374az1 cm3pbi3 _1c374az2"]',
  topickDdate: ":nth-child(3) > :nth-child(1) > .rdp-button_reset",
  topickRdate: ":nth-child(4) > :nth-child(6) > .rdp-button_reset > .css-1h2zojm",
  toselectPass: '[class="css-1jsn6pp"]',
  toselectAdult: '[class="css-vqwtyu"]',
  toselectChild: '[class="css-vqwtyu"]',
  toselectClass: '[class="_1l9hnubc _1l9hnubb"]',
  toclickSearch: '[class="b0x94f5 b0x94f0 b0x94f3 css-zchx5o"]',
};
